openapi: 3.1.0
info:
  title: Tzun Backend API
  version: 1.0.0
  description: Unified API spec for GPT audit logging, issue summarization, and fit scoring.

servers:
  - url: https://tzun-fit-score-api.sandra68.repl.co

paths:

  /log_qa_result:
    post:
      summary: Logs the result of a QA prompt test run
      operationId: logQaResult
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - run_id
                - prompt_id
                - output_score
              properties:
                run_id:
                  type: string
                prompt_id:
                  type: string
                persona_context:
                  type: string
                resume_input:
                  type: string
                jd_input:
                  type: string
                output_score:
                  type: integer
                  minimum: 1
                  maximum: 5
                flagged_issues:
                  type: array
                  items:
                    type: string
                recommendations:
                  type: array
                  items:
                    type: string
                gpt_output:
                  type: string
      responses:
        '200':
          description: Log successfully received
        '400':
          description: Invalid input

  /summarize_issues:
    get:
      summary: Summarizes recent flagged QA issues
      operationId: summarizeIssues
      responses:
        '200':
          description: Top recurring issues and tuning recommendations
          content:
            application/json:
              schema:
                type: object
                properties:
                  top_issues:
                    type: array
                    items:
                      type: string
                  tuning_recommendations:
                    type: array
                    items:
                      type: string
        '500':
          description: Sheet access or processing error

  /fit_score:
    post:
      summary: Compute resume-to-job Fit Score
      operationId: getFitScore
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - resume_text
                - job_description_text
              properties:
                resume_text:
                  type: string
                job_description_text:
                  type: string
      responses:
        '200':
          description: Fit score successfully computed
          content:
            application/json:
              schema:
                type: object
                properties:
                  fit_score:
                    type: integer
                    example: 87
                  match_quality:
                    type: string
                    example: "Strong"
        '400':
          description: Missing input fields
        '500':
          description: Embedding or calculation error
